/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <gtk/gtk.h>
/* Header for class com_baeldung_jni_HelloWorldJNI */

#ifndef _Included_com_baeldung_jni_HelloWorldJNI
#define _Included_com_baeldung_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baeldung_jni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baeldung_jni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_baeldung_jni_HelloWorldJNI
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_baeldung_jni_HelloWorldJNI_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_baeldung_jni_HelloWorldJNI
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_baeldung_jni_HelloWorldJNI_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_baeldung_jni_HelloWorldJNI
 * Method:    multi03
 * Signature: ()Ljava/lang/Double;
 */
JNIEXPORT void JNICALL Java_com_baeldung_jni_HelloWorldJNI_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
